server:
  port: 8080
spring:
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: a
    password: a

  datasource:
    password:
    url: jdbc:h2:mem:local
    username: sa
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
    sql:
      init:
        mode: always
    config:
      activate:
        on-profile: local
    h2:
      console:
        path: /h2-console
        enabled: true